### PR TITLE
Governance doc

### PR DESCRIPTION
**Pull request by edeyoung**
This pull request contains the shared repository governance document and contribution model to ensure easy collaboration between MITRE and the transition organization.

Pull requests into cqm-models require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [x] This pull request describes why these changes were made.
- [x] Code diff has been done and been reviewed

**Bonnie Reviewer:**

Name:
- [x] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose

**Cypress Reviewer:**

Name:
- [x] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose

**Before Merge**
- [ ] Governance doc has been updated with company names as appropriate
- [ ] Governance doc has been updated with mailing lists, etc., as appropriate

### CODE REVIEW

**Comment by edeyoung** [comment]
@dczulada 
Sorry for late response - somehow didn't see that you commented.

"white space only changes" - we've had issues on Bonnie in the past where some people's editors (atom, for instance) would automatically change all pre-existing tabs to spaces. So when they would commit their change, it was hard to tell where the change was. We actually had one or two bugs go through because they were lost in the fog of whitespace changes.
So although yes, we want spaces and not tabs, that type of change should not be combined with substantive changes. So even doing a squash merge wouldn't have helped the situation because there still would have been white space changes everywhere in the PR diff.

re diff/status - yes, i'm suggesting people do it to make sure they don't commit silly stuff.

I'll move the line as you suggest

**Comment by edeyoung** [comment]
@dczulada do you have suggestions on how to clarify the whitespace only changes text based on what I wrote above?

Maybe, "You are not committing junk (e.g., whitespace only changes that distract from substantive changes)"

**Comment by losborne** [comment]
@edeyoung @dczulada Regarding the whitespace only changes conversation above, GitHub now has the option to easily hide whitespace only changes in the PR diff:

image

**Review by dczulada — DISMISSED** [review]

**Comment by edeyoung** [comment]
Waiting on transition contract to be finalized to replace company names and create shared repo mailing lists.

**Pull request closed without merging**
